language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
install:
  - pip install tox
script: tox
matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35
      
