language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
install:
  - pip install tox
script: tox
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5